### ISSUE TITLE
Update Python to 3.11

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/docker-python-web#23]
We're standardizing on this version across the various Benefits related repositories.

**Comment by angela-tran** [comment]
This is where I'm currently at with testing this Python update:

Start from clean slate
- [x] Use Docker Desktop to delete containers and images for Benefits and eligibility-server

Update Python
- [x] Update `docker-python-web` Dockerfile to use `python:3.11`
- [x] Rebuild its image - `docker compose build app --no-cache`
- [x] Check its Python version - `docker compose run --entrypoint "python --version" app`

Test Benefits with updated base image
- [x] Update Benefits Dockerfile to use `docker-python-web:app` (locally built image)
- [x] Rebuild Benefits image - `docker compose build client --no-cache`
- [x] Check its Python version - `docker compose run --entrypoint "python --version" client`
- [x] Open Benefits devcontainer with "Rebuild Without Cache and Reopen in Container"
- [x] Run app locally and go through full flow - did Senior/Login.gov eligibility verification and enrollment, also tested Veteran/Login.gov eligibility with ineligible user
- [x] Verify that unit tests pass

Test eligibility-server with updated base image
- [x] Update eligibility-server Dockerfile to use `docker-python-web:app`
- [x] Rebuild eligibility-server image - `docker compose build server --no-cache`
- [x] Check its Python version - `docker compose run --entrypoint "python --version" server`
- [x] Open eligibility-serve devcontainer with "Rebuild Without Cache and Reopen in Container"
- [x] Update Benefits `compose.yml` to point at local `eligibility_server:latest`
- [x] Run app locally and go through Courtesy Card flow and enrollment
    - ❌ Getting this output
        ```
        2023-09-19 13:44:04 + bin/init.sh
        2023-09-19 13:44:04 + flask init-db
        2023-09-19 13:44:05 [2023-09-19 18:44:05,575] DEBUG urllib3.connectionpool:1048 Starting new HTTPS connection (1): raw.githubusercontent.com:443
        2023-09-19 13:44:05 [2023-09-19 18:44:05,794] DEBUG urllib3.connectionpool:546 https://raw.githubusercontent.com:443 "GET /cal-itp/eligibility-server/dev/data/server.csv HTTP/1.1" 200 2074
        2023-09-19 13:44:05 Traceback (most recent call last):
        2023-09-19 13:44:05   File "/home/calitp/.local/bin/flask", line 8, in <module>
        2023-09-19 13:44:05     sys.exit(main())
        2023-09-19 13:44:05              ^^^^^^
        2023-09-19 13:44:05   File "/home/calitp/.local/lib/python3.11/site-packages/flask/cli.py", line 1064, in main
        2023-09-19 13:44:05     cli.main()
        2023-09-19 13:44:05   File "/home/calitp/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
        2023-09-19 13:44:05     rv = self.invoke(ctx)
        2023-09-19 13:44:05          ^^^^^^^^^^^^^^^^
        2023-09-19 13:44:05   File "/home/calitp/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
        2023-09-19 13:44:05     return _process_result(sub_ctx.command.invoke(sub_ctx))
        2023-09-19 13:44:05                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        2023-09-19 13:44:05   File "/home/calitp/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
        2023-09-19 13:44:05     return ctx.invoke(self.callback, **ctx.params)
        2023-09-19 13:44:05            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        2023-09-19 13:44:05   File "/home/calitp/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
        2023-09-19 13:44:05     return __callback(*args, **kwargs)
        2023-09-19 13:44:05            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        2023-09-19 13:44:05   File "/home/calitp/app/eligibility_server/db/setup.py", line 34, in init_db_command
        2023-09-19 13:44:05     import_users()
        2023-09-19 13:44:05   File "/home/calitp/app/eligibility_server/db/setup.py", line 57, in import_users
        2023-09-19 13:44:05     import_csv_users(path, remote)
        2023-09-19 13:44:05   File "/home/calitp/app/eligibility_server/db/setup.py", line 97, in import_csv_users
        2023-09-19 13:44:05     data = csv.DictReader(
        2023-09-19 13:44:05 Creating table...
        2023-09-19 13:44:05 Table created.
        2023-09-19 13:44:05 Importing users from: https://raw.githubusercontent.com/cal-itp/eligibility-server/dev/data/server.csv
        2023-09-19 13:44:05            ^^^^^^^^^^^^^^^
        2023-09-19 13:44:05   File "/usr/local/lib/python3.11/csv.py", line 86, in __init__
        2023-09-19 13:44:05     self.reader = reader(f, dialect, *args, **kwds)
        2023-09-19 13:44:05                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        2023-09-19 13:44:05 TypeError: "quotechar" must be a 1-character string
        ```
- [ ] Troubleshoot and fix:
   - [x] Revert eligibility-server back to Python 3.10 (point it back to GHCR `docker-python-web`)
   - [x] `docker compose build server --no-cache`
   - [x] Open Benefits devcontainer with "Rebuild With No Cache and Reopen in Container"
   - `server` service was able to start, gives output:
    ```
    2023-09-19 13:51:49 + bin/init.sh
    2023-09-19 13:51:49 + flask init-db
    2023-09-19 13:51:51 [2023-09-19 18:51:51,184] DEBUG urllib3.connectionpool:1048 Starting new HTTPS connection (1): raw.githubusercontent.com:443
    2023-09-19 13:51:51 [2023-09-19 18:51:51,392] DEBUG urllib3.connectionpool:546 https://raw.githubusercontent.com:443 "GET /cal-itp/eligibility-server/dev/data/server.csv HTTP/1.1" 200 2074
    2023-09-19 13:51:52 + nginx
    2023-09-19 13:51:52 + python -m gunicorn -c /home/calitp/run/gunicorn.conf.py eligibility_server.app:app
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [14] [INFO] Starting gunicorn 21.2.0
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [14] [INFO] Listening at: unix:/home/calitp/run/gunicorn.sock (14)
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [14] [INFO] Using worker: sync
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [15] [INFO] Booting worker with pid: 15
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [16] [INFO] Booting worker with pid: 16
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [17] [INFO] Booting worker with pid: 17
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [18] [INFO] Booting worker with pid: 18
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [19] [INFO] Booting worker with pid: 19
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [20] [INFO] Booting worker with pid: 20
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [21] [INFO] Booting worker with pid: 21
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [22] [INFO] Booting worker with pid: 22
    2023-09-19 13:51:54 [2023-09-19 18:51:54 +0000] [23] [INFO] Booting worker with pid: 23
    2023-09-19 13:51:51 Creating table...
    2023-09-19 13:51:51 Table created.
    2023-09-19 13:51:51 Importing users from: https://raw.githubusercontent.com/cal-itp/eligibility-server/dev/data/server.csv
    2023-09-19 13:51:51 Users added: 25
    2023-09-19 13:51:51 Eligibility types added: 1
    ```
  - [ ] Figure out what the difference is
- [ ] Verify that unit tests pass
